### ISSUE TITLE
ReliableSession

### ISSUE THREAD

**Issue by GibSral** [dotnet/wcf#1655]
I try to establish a reliable duplex connection via WCF (netTcpBinding) in UWP.
NetTcpBinding/NetHttpBinding does not offer the possibility to configure a reliable session (option missing in ctor).

Am I missing something?

**Comment by zhenlan** [comment]
@GibSral sorry for running into this. You did not miss anything. Reliable session is currently not supported.

**Comment by zhenlan** [comment]
If we do this, we should consider decoupling reliable session from the transport. Currently, reliable sessions are not usable without an in-box binding.

**Comment by SurendraPhadke** [comment]
Any update on the support of ReliableSession?

**Comment by Lxiamail** [comment]
@SurendraPhadke ReliableSession is very complicated and problemetic in some satuation evens in .NET Framework WCF. Currently, there is no plan to bring the feature to WCF in .NET Core. However, it is helpful to hear if any customer is blocked by missing this feature and why it is a blocking issue. Please continue vote and share your scenario with us.

**Comment by danielleiszen** [comment]
Any news on this? Is there any workaround or existing solution to maintain sessions on the server side?

I am developing a laundry automation system where the information from RFID readers is collected by a windows service and several UWP terminals would be notified about the changes of the data. This would need some kind of session handling on the service side for which per-session WCF service instantiation is a logical choice. (The terminal sessions do not live longer than a few minutes) 
It would be quite painful to reinvent the wheel and develop a session management solution when the technology is already available on .NET Framework for a long time. 

If there is no support for sessions, what other options are suggested as a workaround ? Thank you

**Comment by Alois-xx** [comment]
@Lxiamail: I have seen people using reliable sessions to enforce in order message delivery. Is it true that WCF messages can arrive in a different order than they were sent? I reliable messaging the only way to cure that odd behavior of WCF? 

We are using a (nettcp) duplex commuincation and we have a callback on the service.
Let suppose we call on backend and on different threads:

1.	ICallback.DoSomething(byte[]) with a huge byte array
2.	ICallback.DoSomething(byte[]) with a small byte array.

On client side it is possible that the second call will arrive first if we do not use a reliable session.
And it can mess up our datamodel on client side.

**Comment by krkawalli** [comment]
We trying to consume WCF service with the reliable session (this is older one) , so trying to consume it throw the .NET core , do not find this option yet to set as part of the Custom Binding. 

Can some one give an option on how we can consume Reliable session enabled service in .NET Core.

Error : 
"One or more errors occurred. (The action http://tempuri.org/...../GetDefaultHosts is not supported by this endpoint. Only WS-ReliableMessaging February 2005 messages are processed by this endpoint.)"

**Comment by mconnew** [comment]
After we have the work completed to support WS-Federation, my next big project is to implement reliable sessions. The hope is to have it complete for the .NET 5 release.

**Comment by krkawalli** [comment]
> 
> 
> After we have the work completed to support WS-Federation, my next big project is to implement reliable sessions. The hope is to have it complete for the .NET 5 release.

That means - we do not have any way to consume Reliable Session Enabled WCF in .NET Core now?

**Comment by krkawalli** [comment]
> 
> 
> @SurendraPhadke ReliableSession is very complicated and problemetic in some satuation evens in .NET Framework WCF. Currently, there is no plan to bring the feature to WCF in .NET Core. However, it is helpful to hear if any customer is blocked by missing this feature and why it is a blocking issue. Please continue vote and share your scenario with us.

-Yes we are blocked to consume some of the data which is being exposed by WCF service which has reliable session enabled by WCF service. Since we moving all the old .NET code to .NET core , this is one think which has blocked us to completely move to .NET Core.

**Comment by Henk7** [comment]
> @SurendraPhadke ReliableSession is very complicated and problemetic in some satuation evens in .NET Framework WCF. Currently, there is no plan to bring the feature to WCF in .NET Core. However, it is helpful to hear if any customer is blocked by missing this feature and why it is a blocking issue. Please continue vote and share your scenario with us.

Hi,
Also depending on a third party service which is using ReliableSession. The endpoint throws "Only WS-ReliableMessaging February 2005 messages are processed by this endpoint."
We have control over the client code but not the server.
Is there a workaround in netcore3.1?

**Comment by LouisCPro** [comment]
Hi,

Same Problem for me trying to port a Framework based WCF Duplex Service to UWP to create a new IHM under Win10IotCore.
No RealiableSession property in NetTcpBinding !

**Comment by LouisCPro** [comment]
Notic Also that even Instancecontext is not supported.

Here is the way I initialize my clientservice in classic WCF :

"...
m_ServiceCallback = new MyClientInstanceCallback();
m_InstanceContext = new InstanceContext(m_ServiceCallback);
m_Client = new MyDBClient(m_InstanceContext);
m_Client.ChannelFactory.Closed += ChannelFactory_Closed;
m_Client.ChannelFactory.Faulted += ChannelFactory_Faulted;

This constructor is marked as private in UWP Service Reference, and however I use a partial implementation to enable a new constructor in public, it throws a NotSupportedException....

**Comment by mconnew** [comment]
I just committed the reliable sessions implementation. While this is shipping as part of the overall .NET 5 release, WCF continues to only depend on netstandard2.0 so new features are enabled for all supported versions of .NET Core and you do not need to move to .NET 5 to use these new features.

**Comment by ssa3512** [comment]
@mconnew I pulled latest master and built the service model packages but can't get a reliable session one way call to work under netcore3.1. Getting this assertion:

```
Process terminated. Assertion failed.
Type 'System.ServiceModel.Channels.ReliableOutputSessionChannelOverDuplex' is required to override OnOpenAsync
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout) in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 561
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout) in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 532
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout) in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 504
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout) in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs:line 498
   at System.Runtime.TaskHelpers.CallActionAsync[TArg](Action`1 action, TArg argument) in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\Internals\System\Runtime\TaskHelpers.cs:line 377
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.<>c.<System.Runtime.CompilerServices.IStateMachineBoxAwareAwaiter.AwaitUnsafeOnCompleted>b__5_0(Object s)
   at System.Runtime.ServiceModelSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0(Object s) in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\Internals\System\Runtime\ServiceModelSynchronizationContext.cs:line 15
   at System.Runtime.IOThreadScheduler.ScheduledOverlapped.Callback() in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\Internals\System\Runtime\IOThreadScheduler.cs:line 461
   at System.Runtime.IOThreadScheduler.ScheduledOverlapped.IOCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\Internals\System\Runtime\IOThreadScheduler.cs:line 434
   at System.Runtime.Fx.IOCompletionThunk.UnhandledExceptionFrame(UInt32 error, UInt32 bytesRead, NativeOverlapped* nativeOverlapped) in C:\Projects\dotnet\wcf\src\System.Private.ServiceModel\src\Internals\System\Runtime\Fx.cs:line 485
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

Repro here:
https://github.com/ssa3512/wcf-reliable-sessions

With service host project running
`dotnet run -f net472 --project .\wcfasynctestclient\wcfasynctestclient.csproj` succeeds
`dotnet run -f netcoreapp3.1 --project .\wcfasynctestclient\wcfasynctestclient.csproj` fails

Am I missing something?

**Comment by mconnew** [comment]
@ssa3512, oops that's a bug. It should be an easy fix but it might be tight to get it in before we release the final build. I'll try, but if it doesn't make it into the final build, I'll get it out in the first patch release which should be a month later.

**Comment by mconnew** [comment]
Fix is in PR #4395, it should get merged tomorrow.

**Comment by mconnew** [comment]
@ssa3512, the fix is merged now. Can you try that out and confirm your issue is fixed.

**Comment by ssa3512** [comment]
@mconnew Thanks - I verified it is working as expected now.

**Comment by xnlu** [comment]
Hi when will this feature be available in NuGet? I just download the latest System.ServiceModel.NetTcp package, 4.8.0-preview3.20412.3. But reliable sessions implementation is not included yet. Thanks!

**Comment by mconnew** [comment]
It will published to nuget at the same time .Net 5 is released which happens next month. I can't say more than that as I don't know if a more definite release date has been announced publicly yet and I don't want to be the guy to announce an internal schedule by mistake!

**Comment by rughvi** [comment]
HI there,
I am still unable to have a success with 'reliableSession' binding in any of the following clients:
.Net Core 3.1
.Net standard 2
.Net 5

My wcf service is running as a .net framework 4.7.2.

I tried both wsHttpBinding and CustomBinding. 

Am I missing anything?

How can I achieve 'reliableSession' in .Net Core 3.1 client talking to .Net framework 4.7 server setup with 'reliableSession' binding.

Thanks
