### ISSUE TITLE
Add Mtom support in WCF runtime

### ISSUE THREAD

**Issue by chris5287** [dotnet/wcf#1810]
I am getting the following error when using the Visual Studio WCF Connected Service extension for Visual Studio 2017:

```
Scaffolding Code ...
Error:Warning: The following Policy Assertions were not Imported:   XPath://wsdl:definitions[@targetNamespace='http://imaging.oracle/']/wsdl:binding[@name='DocumentContentServicePortBinding']
  Assertions:
    <ns1:OptimizedMimeSerialization xmlns:ns1='http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization'>..</ns1:OptimizedMimeSerialization>
Warning: Unsupported binding element type: 'System.ServiceModel.Channels.UnrecognizedAssertionsBindingElement'.
Warning: Unsupported message encoding element type: 'System.ServiceModel.Channels.MtomMessageEncodingBindingElement'. It must be one of the following types: 'System.ServiceModel.Channels.BinaryMessageEncodingBindingElement', 'System.ServiceModel.Channels.TextMessageEncodingBindingElement.'
Warning: Endpoint 'DocumentContentServicePort' at address 'http://localhost/imaging/ws/DocumentContentService' contains one or more bindings not compatible with .Net Core apps, skipping...
Error: No endpoints compatible with .Net Core apps were found.
Failed to generate service reference.
```

The WSDL/XSD file causing the issue:
[DocumentContentService.xsd.txt](https://github.com/dotnet/wcf/files/840688/DocumentContentService.xsd.txt)
[DocumentContentService.wsdl.txt](https://github.com/dotnet/wcf/files/840687/DocumentContentService.wsdl.txt)

dotnet --info
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by hongdai** [comment]
Hi Chris, this is because WCF runtime currently does not support Mtom. Potential workaround is try to disable Mtom on the service side if you have access to the service.

If your scenario needs Mtom support, please go ahead open a issue for WCF runtime to consider adding the support.

Thanks,
Hong

**Comment by chris5287** [comment]
Hi Hong, I'm afraid I do not have control over the server side :(

Where do I need to raise the issue to add Mtom support, or does this issue already cover it?

**Comment by hongdai** [comment]
I think you can rename this issue to add Mtom support in WCF runtime. We share the same git Repro.

**Comment by OkuraSt** [comment]
same here @eserozvataf 

Do you have any workarounds for consuming this type of SAP WS in net core?

Warning: Endpoint 'ZBWS_MAT_STOCKALMACEN' at address 'http://lcs03..local:8000/sap/bc/srt/rfc/sap/zws_mat_stockalmacen/200/zws_mat_stockalmacen/zbws_mat_stockalmacen' contains one or more bindings not compatible with .Net Core apps, skipping...
Error: No endpoints compatible with .Net Core apps were found.

Failed to generate service reference.

**Comment by suadev** [comment]
Same here :(

**Comment by felipecaputo** [comment]
Hello folks! Is there any chance to get this implemented?

**Comment by zhenlan** [comment]
Not in a plan at this point. Please upvote if this is important. It will be helpful for future planning.

**Comment by felipecaputo** [comment]
The content type multipart/related; type=\"application/xop+xml\" ... start-info=\"text/xml\" of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly

There is any way I can add a custom decoder to receive this message, while it isn't supported yet?

**Comment by Kantuz001** [comment]
Same problem(

**Comment by napalm684** [comment]
Has anyone figured out a work around?  I can get the action to occur via the SOAP call but the response is what is failing.  Even if I could get the string of the response (which is in the exception message) I could parse what I need out of it as a short term fix.

**Comment by felipecaputo** [comment]
not yet :(

**Comment by dnbr2002** [comment]
We could really use some support for this and were hoping with dotnet core 2.0 it might get included.  Any chance it's being added in a future release?

**Comment by rezvanf** [comment]
I have the same problem 

I've tried to consume a java SOAP without mtom enabled, and it accepted my request, but the response came with xop/xml.

What i don't understand is at the supported features for .net core 1.0

https://github.com/dotnet/wcf/blob/master/release-notes/SupportedFeatures-v1.0.0.md

It shows message encoding for both text and binary supported. 

So how do we do this please if we are consuming WCF services in our .net core apps and need message encoding of WSEncoding.Mtom

**Comment by mconnew** [comment]
I thought I would give some background on why this isn't a trivial task. This isn't a case of simply copying the code over. On the full framework we use HttpWebRequest for sending an HTTP request. We get the request stream from HttpWebRequest and then write the request message to it.  

In .Net Core, we don't have HttpWebRequest available and so need to use HttpClient instead. This has a completely different model for sending a request, you pass it a class derived from HttpContent and HttpClient will request a stream from the HttpContent which it can read from and will subsequently write out to it's internal request stream. This meant that about 75% of the Http transport was basically a rewrite. We encapsulate the request message inside our own HttpContent class and when the request bytes are needed, we use the MessageEncoder to encode the message and then return that. This works well because the channel layer abstraction boundaries are cleanly observed.  

The problem with MTOM is that how it's implemented on the full framework the clean api boundaries between the transport and MessageEncoder were trampled on by a herd of angry elk. With the reversal of data flow (HttpClient pulls from HttpContent instead of WCF pushing to HttpWebRequest's request stream), we will need to do a complete rewrite of the MTOM feature and probably refactor the current code so that HttpRequestMessage/HttpResponseMessage are the encapsulation boundary instead of HttpContent.  

If I was working on this full time with no other tasks to work on, I would estimate it would take me about 2 months to get it to a preview state. We're aware there are some shortcomings in the full framework implementation such as the inability to precisely control which fields are placed into their own multi-part section and which are serialized inline so any rewrite would also have an eye to making sure we have a path to exposing a clean way to control this as it has been a major pain point for some.  

Hopefully this explanation helps you understand why we haven't simply ported the feature at this point.

**Comment by felipecaputo** [comment]
@mconnew I don't know the framework too well, but with the right direction I would really like to do it, having the right direction to do it.

It seems really a complex implementation but, may more people would like to help if you can spare some time in tutoring or breaking it into small implementations we could do to take advantage of the OpenSource community?

Do you think it could be possible?

**Comment by malsoft-pl** [comment]
Same problem(

**Comment by pieruz** [comment]
I have this response from a service:

--MIMEBoundary_59f98a3b863640e46b622e5739083846dab4b1825abc60d0
Content-Type: application/xop+xml; charset=UTF-8; type="text/xml"
Content-Transfer-Encoding: binary
Content-ID: 
<0.49f98a3b863640e46b622e5739083846dab4b1825abc60d0@apache.org>


--MIMEBoundary_59f98a3b863640e46b622e5739083846dab4b1825abc60d0--

<ns2:res xmlns:ns2="http:/xxxxx/v1.0/types">
    <ID>1162898</ID>
    <DataOraRicezione>2018-03-13T15:08:30.119+01:00</DataOraRicezione>
</ns2:res>

How can I convert it easily to an xml? I have the class created from the xsd, but the MTOM header is annoying me.....

**Comment by mananchoksi007** [comment]
Receives Below Error

0202Unable to unmarshal XML stream. Please verify and resubmit.::Premature end of file.Invalid input

Its successfully working with .Net Framework. Is there different way to post the xml content then .Net framework soap service call?

**Comment by jducobu** [comment]
The status please ?

**Comment by lalenzos** [comment]
Are there any news regarding ASP.NET Core and SOAP MTOM?

**Comment by brux88** [comment]
are there news?

**Comment by jducobu** [comment]
Non news ... :(
Personaly, i added a binding supported by .net core and use it

**Comment by Trapulo** [comment]
I moved my WS to the old .NET 4.6 and WCF :(

**Comment by brux88** [comment]
I have a .net core project, I created another .net 4.5 project to be able to use mtom. this last project the amount in my project core.net. but it gives me an error:Method not found: 'Void System.ServiceModel.BasicHttpsBinding.set_MessageEncoding(System.ServiceModel.WSMessageEncoding)'.


why?

**Comment by mananchoksi007** [comment]
Same, I had also put that service call in to .net Framework as .net core
wont be able to handle that. Thats so disappointing

**Comment by johntobia** [comment]
This is one of my organizations only blockers moving to .NET Core. We have a document management platform that returns large documents using MTOM (that we have no control over).  We have successfully written a wrapper using the XmlMtomReader class (and all other related / needed classes). We really just need XmlMtomReader and XmlMtomWriter ported to .NET Core. I realize that the WCF stuff is more involved, but would it be possible just to get the underlying classes implemented?

**Comment by felipecaputo** [comment]
> 
> 
> Non news ... :(
> Personaly, i added a binding supported by .net core and use it

Can you share how did you did it?

**Comment by cesaralc** [comment]
Hi, Any update? This is a fairly important feature.

**Comment by brux88** [comment]
> > Non news ... :(
> > Personaly, i added a binding supported by .net core and use it
> 
> @jducobu Can you share how did you did it?


yes its possible share how did you did it?

**Comment by napalm684** [comment]
Agreed sharing is caring :-)

**Comment by jducobu** [comment]
Instead of using Mtom binding, i use a basichttpbinding (or something like that). But for that, the service must ne configured to use this binding configuration.

**Comment by jducobu** [comment]
Mtom was abandonned in 2012 by microsoft because the protocol is slower than json.

**Comment by LokiMidgard** [comment]
Unless you consume someone elses Service where you can't change any configuration.

**Comment by jducobu** [comment]
I understand. In my case i have chance the service provide also using httpbasic supported by .net core. You cab also offered a wrapper behind the wcfservice in rest in .net framework using mtom if it's the only binding the service offers. I'll do that if i'm in your situation

**Comment by Trapulo** [comment]
I understand that Mtom can be "dead". But interoperability is interoperability. For example, in Italy the government has created a mandatory service to manage all invoices of all country. Every company may use it. And this service is based on IBM+Java (ok, I know... sorry, we're in Italy, we like to be late) and requires Mtom. So, every ERP based on .NET cannot be in .NET Core and will require some legacy module in WCF 4 to bridge the two world.

**Comment by felipecaputo** [comment]
@Trapulo Not just Italy has legacy integrations that uses Mtom, here in Brazil the software that runs on some law courts that provide a mandatory integration to others law courts is mandatory and uses Mtom too. 

We are having the same problem and this is the only thing that is blocking us to migrate our services.

**Comment by napalm684** [comment]
A vendor product is our issue.  We don't control the service implementation of OpenText.

**Comment by cruentusmors** [comment]
Trying to consume web service from peoplesoft using .net core - this needs to work

**Comment by hickmanjos** [comment]
It's also still widely used in the states, the IRS is still using MTOM.

(I'm currently on the path of restarting my project with .net framework)

**Comment by brux88** [comment]
at today nothing news? :(

**Comment by brux88** [comment]
there is a guide to be able to deserialize a mtom in aspnet core

**Comment by felipecaputo** [comment]
@brux88 Are you asking if there is a guide? Or telling that there is a guide because, if this guide exists, I'ld love to read it.

**Comment by brux88** [comment]
@felipecaputo I'm looking for a guide, I can not believe that this issue has not been put even in the next milestone for two years, so I wanted to know if there were other ways to avoid the problem

**Comment by felipecaputo** [comment]
Hi @Lxiamail it would be possible to have some definitions / specification about how this should be implemented and maybe the community could provide the implementation... 

I really thing that this would make a lot of people really happy o>

**Comment by JohnTobia** [comment]
@felipecaputo see my comment above.  To start, we really just need XmlMtomReader and XmlMtomWriter ported to .NET Core.  I have a working solution (by all means not optimal) if those classes exist.  It's at least a starting point.

**Comment by felipecaputo** [comment]
@JohnTobia I'll take a look when I get home today, maybe I can help and end up submitting a PR

**Comment by kfrancis** [comment]
@felipecaputo @JohnTobia I'd be willing to donate my time to this issue. We need this. I need a .NET Standard compatible library. How can we organize and get this done?

@JohnTobia Can you gist what you've done that works in your scenario?

**Comment by naveen4854** [comment]
Any update on the Mtom support?

**Comment by chrisengelsma** [comment]
Also wondering this, the MTOM support is the only thing still keeping me on .NET framework

**Comment by tstefansson** [comment]
Any update on the Mtom support?

**Comment by brux88** [comment]
@Lxiamail please any update on the mtom support

**Comment by Lxiamail** [comment]
Unfortunately, we don't have any further update on this. We also considered to define a spec so that community may be able to help to do the implementation. However, as Matt commented above, the primary complexity is redesign the feature on .NET Core. The investigation cost to define the spec will be high that we can't afford at this point.

**Comment by felipecaputo** [comment]
@Lxiamail, if we analise and make a proposal in spec, the team would take a look and evaluate it?

**Comment by mconnew** [comment]
Hi @felipecaputo. Having the community implement MTOM would be great. In the next couple of days I'll write up a quick summary of my thoughts on how to bring in MTOM support including some potential design ideas I've had for a whiile to improve interop with other stacks, and then you can come back with a spec proposal. Does that sound like it would work for you?

**Comment by felipecaputo** [comment]
That would be great. 

I'll wait for these ideas, and take a look at the source and documentation to get ready.

Thank you @mconnew

**Comment by kfrancis** [comment]
Adding a specific chat room for us to discuss: https://gitter.im/wcf-mtom/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by jducobu** [comment]
https://www.w3.org/TR/soap12-mtom/

**Comment by mconnew** [comment]
So here's my brain dump on the topic of MTOM. I've had two strong goals when porting WCF to .NET Core.

**Make code simpler**  
Internally we've mostly dropped APM implementations and everything is Task based. The sync code path has also been dropped and just calls the Task based API's.  

**Own less code**  
WCF on .NET Framework was developed when a lot of what is now taken for granted as existing in the framework just didn't exist so there's a lot of wheels which were invented which have been reinvented and now available generally in the rest of the framework. Nobody went back and removed the WCF implementation and switched to the general one. So the .NET Framework implementation is a lot bigger than it needs to be.

There's some problems with the MTOM implementation which I've become aware of from customers over the years while working on .NET Framework. There are two I'd like to address in a .NET Core implementation. The first one is lack of control in which elements get moved out to separate parts in the HTML multi-part message and which ones get serialized as part of the XML body. The MTOM spec is not opinionated on this and WCF has a heuristic to make this choice. There are some other SOAP stacks which don't like WCF's heuristic. So we should add a mechanism to override the heuristic decision for individual elements to improve interop capability with other stacks. The second problem is the .NET Framework implementation is not extendable through either derivation or encapsulation. The behavior needs to be modifiable by either encapsulation or derivation as there have been multiple issues developers have had over the years which could have been easily addressed if the MTOM encoder behavior could be modified in one of these ways.

The .NET Core implementation of HttpTransportBindingElement is almost a rewrite of the code from .NET Framework. This was needed due to HttpWebRequest not being available (there's a class there now, but it has many undesirable behaviors like forced buffering of the request and isn't the real thing). So the transport was redone using HttpClient. The HttpRequestMessage content is a custom type System.ServiceModel.Channels.MessageContent in order to do things the HttpClient way. Conceptually it lazily does the work of encoding the message when HttpClient is ready to send the body. The reason for this is streamed transfer mode prohibits creating the body up from.  
There is a class System.Net.Http.MultipartContent which looks like a good candidate for use with MTOM. This is the principal of "own less code". There are going to be lots of edge cases in the implementation of Multi-part entity bodies and I prefer if those edge cases were somebody else's problem :). Building on top of MultipartContent will simplify the code a lot. The class also has been written in a way to be convenient to derive so we might want to consider making an MtomMessageContent class which derives from MultipartContent. That might not be necessary though as it's a container of a list of innner HttpContent objects and this inner objects can generate their byte stream lazily.

**Comment by lennykean** [comment]
I developed a workaround to support MTOM in .net core wcf. 
https://github.com/lennykean/WcfCoreMtomEncoder

This is really a workaround that is only meant to consume existing mtom soap services, but I think it could evolve into a full implementation of mtom in .net core.

**Comment by mconnew** [comment]
@lennykean, this looks like a great start. I've had a look at the code behind the ReadAsMultipartAsync method and it has one really big flaw. It reads the entire contents into memory. The typical usage I've seen with the MTOM encoder has been when needing to transfer large amounts of data over a SOAP service. Normally SOAP will encode a byte[] as base64 encoded string which increases it's size by ~30%. This is a lot when transferring 200MB of data. MTOM doesn't really gain you much unless you are sending large amounts of data. It might be possible to use the building blocks in the Microsoft.AspNet.WebApi.Client package to build something better. Basically an implementation of ReadAsMultipartAsync needs to lazily create each of the contained HttpContent objects. The HttpContent parts also need to return a stream from ReadAsStreamAsync which isn't backed by an in memory buffer but read from the actual network stream and fake an EOF once the part has been completely read.  
What you've provided is great if you aren't returning a large amount of data, and the limitations are mainly in the Microsoft.AspNet.WebApi.Client code.

**Comment by matthiaslischka** [comment]
Any updates or reasonable workarounds for big data streaming via mtom?
We need to stream-download big files via SOAP mtom in dotnet core.

**Comment by RealHabix** [comment]
> zhenlan commented on Sep 28, 2017
> Not in a plan at this point. Please upvote if this is important. It will be helpful for future planning.

How much more upvote and time do you guys need (since it's in backlog for 2+ years)?

**Comment by DiegoAndes** [comment]
2020 and we still don't have the implementation :'(

**Comment by craffael** [comment]
I successfully used https://github.com/lennykean/WcfCoreMtomEncoder to read mtom messages. However for writing it doesn't work yet...

**Comment by matthiaslischka** [comment]
This was already mentioned above. Keep in mind that it does not support streaming, the main advantage of MTOM.

**Comment by xtrem14** [comment]
> I developed a workaround to support MTOM in .net core wcf.
> https://github.com/lennykean/WcfCoreMtomEncoder
> 
> This is really a workaround that is only meant to consume existing mtom soap services, but I think it could evolve into a full implementation of mtom in .net core.

Thank's for this.
May not working with HttpsTransportBindingElement :/

**Comment by LokiMidgard** [comment]
@xtrem14 I have it working with https without problems.

See [Client service missmatch](https://github.com/lennykean/WcfCoreMtomEncoder/issues/9#issuecomment-572447799) issue.

**Comment by xtrem14** [comment]
@LokiMidgard thanks for your reply.

I initialized the version of the messages in Soap11.
I now get a whole other error: _A security error was encountered when verifying the message_

`at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()`

I admit that I don't really understand this error ...

**Comment by LokiMidgard** [comment]
@xtrem14 Unforuntaly For me it just worked that way and I havn't worked with it in some time. According to a [stackoverflow question](https://stackoverflow.com/questions/24099136/wcf-authentication-an-error-occurred-when-verifying-security-for-the-message) you may find a more specific error in the event log.

**Comment by xtrem14** [comment]
@LokiMidgard i found my problem, this was due to a WS security problem.
Also not supported by WcfCore.

I solved this one thanks to this solution: https://bbrauns1.wordpress.com/2019/11/07/how-to-add-soap-ws-security-usernametoken-profile-to-net-core-3-0-client/

**Comment by mconnew** [comment]
@xtrem14, we do support usernametoken profile. If you use WSHttpBinding with security mode TransportWithMessageCredentials and client credential mode of Username, it should all work. You might need to turn off establish security context if the remote endpoint isn't using WS-SecureConversation.

**Comment by xtrem14** [comment]
@mconnew, i had actually considered this solution, but WSHttpBinding does not seem to be available in .NET Core : https://docs.microsoft.com/fr-fr/dotnet/api/system.servicemodel.wshttpbinding?view=netframework-4.8&viewFallbackFrom=netcore-3.1

**Comment by mconnew** [comment]
@xtrem14, that's a documentation issue. It's definitely there.

**Comment by mjehle82** [comment]
Is there a time schedule for the MTOM support?
My project will run for the next two years. It would help us decide which way to go.

**Comment by yalin78** [comment]
Is MTOM supported with .net core now? When is it going to be available?

**Comment by ericnewton76** [comment]
So I thought I'd mention this here, since I had to spend an hour or so fully understanding whats going on:

WCF for Net Core made an architectural decision without realizing it prevented MTOM encoding efficiently.
WCF for Net Core team do not want to rearchitect WCF for Net Core.
WCF for Net Core is now recommending gRPC instead.

https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/why-grpc

Do I have this right?

**Comment by ericnewton76** [comment]
Also of note, an external mtom encoder was created: https://github.com/lennykean/WcfCoreMtomEncoder

However, I must stress that due to the architecture limits placed by WCF for Net Core, this WcfCoreMtomEncoder is VERY MEMORY INTENSIVE (according to current implementation, I havent fully examined it myself yet).  Meaning, it has to keep the whole contents in memory before it can emit a valid soap message to the client, which is a suboptimal but workable way to accomplish this.

**Comment by RealHabix** [comment]
> So I thought I'd mention this here, since I had to spend an hour or so fully understanding whats going on:
> 
> WCF for Net Core made an architectural decision without realizing it prevented MTOM encoding efficiently.
> WCF for Net Core team do not want to rearchitect WCF for Net Core.
> WCF for Net Core is now recommending gRPC instead.
> 
> https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/why-grpc
> 
> Do I have this right?

Yes, yes, yes. But what should we do about legacy services that require MTOM - we use plenty and they won't be updated any time soon. Also the WcfCoreMtomEncoder doesn't support streams. Only useful in special cases.

WCF team let us and our customers down big time. We had to switch back to .net framework in many cases.

**Comment by mdora5251** [comment]
> I developed a workaround to support MTOM in .net core wcf.
> https://github.com/lennykean/WcfCoreMtomEncoder
> 
> This is really a workaround that is only meant to consume existing mtom soap services, but I think it could evolve into a full implementation of mtom in .net core.

As far as I understand, I am thinking this just manipulate response part therefore it not possible send request with mtom coding. I already tried in code but message still going with soap+xml.

**Comment by nalincb** [comment]
Recently we wanted to upload files to a WCF service (which used MTOM encoding) from a .NET Core 3.1 client. Below is what worked for us at the end. Hope this will help someone.

```
var textMessageEncodingBindingElement = new TextMessageEncodingBindingElement
                    {
                        MessageVersion = MessageVersion.Soap11,
                        ReaderQuotas =  { ... }
                    };

var mtomMessageEncoderBindingElement = new MtomMessageEncoderBindingElement(textMessageEncodingBindingElement);
var transportBindingElement = new HttpTransportBindingElement { ... };

var binding = new CustomBinding(textMessageEncodingBindingElement, transportBindingElement);
var channelFactory = new ChannelFactory(binding, new EndpointAddress("endpoint"));
var channel = channelFactory.CreateChannel()

```

**Comment by andersonaap** [comment]
@nalincb, should it be?

`var binding = new CustomBinding(mtomMessageEncoderBindingElement, transportBindingElement);`

it works for me.

**Comment by nalincb** [comment]
@andersonaap , yes that was a mistake and I updated code. Cheers.

**Comment by airhawk777** [comment]
Is there ETA on this one?
We are trying to do some long term planning and are keen to move to .NET 5, but this is looking like the only impediment. Changing the server is not an option since its a government service that we consume and have no control over.
Issue is three years old and made 'Priority 1' nine months ago, but it looks like there has be no traction in that time. Is Microsoft committing to this piece of work or still undecided?

**Comment by RealHabix** [comment]
> Is there ETA on this one?
> We are trying to do some long term planning and are keen to move to .NET 5, but this is looking like the only impediment. Changing the server is not an option since its a government service that we consume and have no control over.
> Issue is three years old and made 'Priority 1' nine months ago, but it looks like there has be no traction in that time. Is Microsoft committing to this piece of work or still undecided?

Milestone
6.0

**Comment by mconnew** [comment]
As @RealHabix pointed out, the plan is to have this work completed for the release which aligns with the .NET 6 release. Note that we still only depend on netstandard 2.0 so we won't have a requirement of .NET 6 to use it. All currently supported versions of .NET/.NET Core support netstandard 2.0 so there shouldn't be forced to update your application to use it. This will continue to be our plan until there's a feature that requires .NET 6.

**Comment by NicholasNoise** [comment]
6.0 Preview 2 is already here, but `XmlDictionaryReader.CreateMtomReader` still throws exception.
Any news?

**Comment by tclopes** [comment]
Any news about supporting MTOM?

**Comment by mconnew** [comment]
Good news, Mtom support has now been posted as a PR!!

**Comment by chempro** [comment]
This is great, nice wok
Is there a rough ETA on release date?

**Comment by mconnew** [comment]
It will be available in the upcoming RC release for .NET 6. Just a reminder, WCF doesn't require .NET 6 to use our latest packages and until we have a reason to do so, our latest packages will continue to work on all supported version of .NET. We don't have a lot of code churn in the WCF client code, it's mostly adding stuff so you can have a high level of confidence in the stability of pre-release versions.

**Comment by bcallaghan-et** [comment]
I have installed `System.ServiceModel.Http` version 4.9.0-rc1.21431.2 to experiment with the new MTOM feature, but I cannot instantiate the `MtomMessageEncodingBindingElement` to use with my `CustomBinding`. Instead, I get the following compiler error
```
The type of namespace name 'MtomMessageEncodingBindingElement' could not be found (are you missing a using directive or an assembly reference?)
```
I have ensured that all of my NuGet packages are up-to-date (all ServiceModel packages are 4.9.0-rc1, clean, rebuild). Using dotPeek, I can open the System.Private.ServiceModel assembly and see the binding element there, in the namespace I expected. I've double-checked the source code to verify that the class is public. What am I missing?

**Comment by mconnew** [comment]
@bcallaghan-et, apparently I forgot to add the MtomMessageEncodingBindingElement to the reference assembly itself. You can use it by specifying it's usage with any of the various bindings. For example, BasicHttpBinding has a MessageEncoding property that allows you to specify MTOM. If you need a standalone binding element, you should be able to extract an instance from a binding and set the MessageVersion to be what you need. So for example:
```c#
var binding = new BasicHttpBinding { MessageEncoding = WSMessageEncoding.Mtom };
MessageEncodingBindingElement mebe = binding.CreateBindingElements().Find<MessageEncodingBindingElement>();
mebe.MessageVersion = MessageVersion.Soap12;
```

We'll get it added to the reference assembly before the final release.

**Comment by bcallaghan-et** [comment]
@mconnew Thank you for the workaround. I need to use MTOM with a custom binding, as the remote service requires both Basic auth **and** client certificates, and I couldn't find a way to do that with the `BasicHttpsBinding`. This issue isn't as urgent as I thought, so I can wait for the final release.

**Comment by NicholasNoise** [comment]
@mconnew I do not use WCF itself, but parse MTOM responses. So code that was valid using netfx is no longer `the correct way to do things`. Is a workaround here for me?
```
        public static XmlDocument MtomToXml(Stream stream)
        {
            stream.Seek(0, SeekOrigin.Begin);
            using var reader = XmlDictionaryReader.CreateMtomReader(stream, Encoding.UTF8, XmlDictionaryReaderQuotas.Max);
            var doc = new XmlDocument();
            doc.Load(reader);
            return doc;
        }
```

**Comment by NicholasNoise** [comment]
@mconnew any news mate?

**Comment by mconnew** [comment]
Sorry I forgot to respond to your last comment. The easiest way to do this I believe is to use the MtomMessageEncodingBindingElement. This will output a Message object. Depending on how you want to parse things, I don't know how appropriate this is to your use case. Presuming you want to minimize changes elsewhere in the code, this can be converted to an XmlDocument. Here's some example code on how to do this. You might need to tweak it for your scenario a bit if the SOAP/Envelope version is different than the default. Something like this should work for you:
```c#
            var mtomBE = new MtomMessageEncodingBindingElement(MessageVersion.Default, Encoding.UTF8);
            var encoderFactory = mtomBE.CreateMessageEncoderFactory();
            var encoder = encoderFactory.Encoder;
            var message = encoder.ReadMessage(stream, int.MaxValue);
            var messageBufferedCopy = message.CreateBufferedCopy(int.MaxValue);
            var writableMessage = messageBufferedCopy.CreateMessage();
            XmlDocument doc = new XmlDocument();
            using (XmlWriter xmlDocWriter = doc.CreateNavigator().AppendChild())
            {
                using (XmlDictionaryWriter writer = XmlDictionaryWriter.CreateDictionaryWriter(xmlDocWriter))
                {
                    writableMessage.WriteMessage(writer);
                }
            }
```
Let me know if that works for you or if you hit any problems. I couldn't test this code as I don't have an Mtom stream lying around handily to test this so it might need some tweaks.  

I'm curious why you are using the MtomReader directly instead of using WCF to do the work? You can use WCF in a contractless way using the IRequestChannel interface to make a request and get a reply using Message objects. Typically you would do this if the request or reply message if a little too free form for a contract definition. Going low level like this is usually a result of not knowing how to get WCF to go a little lower level. XmlDocument isn't as performant as XmlReader (which is what WCF uses to expose the body) and I wonder if there might be a better way to achieve your end goal. I often find taking a step back and looking at the original problem which is needing to be solved can lead to a simpler/cleaner solution.

**Comment by JoaoSaDevdotNet** [comment]
Someone Fix it? I got the issue Message Transmission Optimization Mechanism (MTOM) message encoding is not supported on this platform every time I try.

**Comment by spodskubka** [comment]
@JoaoSaDevdotNet what do you need fixed? It's very hard to help you based on that kind of error description.

Do you have an actual code sample? Maybe with a list of referenced NuGet packages and their versions?

Then somebody may be able to tell you what the problem is. 👍

**Comment by JoaoSaDevdotNet** [comment]
> stream.Seek(0, SeekOrigin.Begin);
>             using var reader = XmlDictionaryReader.CreateMtomReader(stream, Encoding.UTF8, XmlDictionaryReaderQuotas.Max);
>             var doc = new XmlDocument();
>             doc.Load(reader);
>             return doc;

I tried to use your solution but I am getting the error The expected encoding 'utf-16LE' does not match the actual encoding 'utf-16BE'. Do you know what means?  I can't be able to found nothing about.

**Comment by josef-moser** [comment]
Dear sender,

CGM is temporarily not reachable in some regions via the usual eMail addresses and landline numbers.  In these cases, please feel free to use SMS and mobile telephony of your individual contact persons, as far as they are known to you or inform yourself about further contact possibilities via the respective company or product page.  

Thank you for your understanding and best regards, 
Your CGM Team  

-------------------------

Sehr geehrte Absenderin, 
sehr geehrter Absender,

CGM ist in einigen Regionen vorübergehend nicht über die gewohnten eMail-Adressen und Festnetznummern erreichbar.  Bitte nutzen Sie gerne in diesem Fall SMS und Mobilfunk-Telefonie Ihrer individuellen Ansprechpartner, soweit diese ihnen bekannt sind oder informieren Sie sich über die jeweilige Firmen- bzw. Produktseite über weitere Kontaktmöglichkeiten. 

Vielen Dank für Ihr Verständnis und freundliche Grüße,  
Ihr CGM-Team

**Comment by JoaoSaDevdotNet** [comment]
> @JoaoSaDevdotNet what do you need fixed? It's very hard to help you based on that kind of error description.
> 
> Do you have an actual code sample? Maybe with a list of referenced NuGet packages and their versions?
> 
> Then somebody may be able to tell you what the problem is. 👍

Okay follow the code

using var mtomMessageInMemory = new MemoryStream(xml);
var dataSerializer = new DataContractSerializer(typeof(ReturningType));

Here i get the error I said
var reader = XmlDictionaryReader.CreateMtomReader(mtomMessageInMemory, Encoding.UTF8, lDictionaryReaderQuotas.Max);



return (ReturningType)dataSerializer.ReadObject(reader);

**Comment by mconnew** [comment]
@JoaoSaDevdotNet , try replacing `Encoding.UTF8` with `Encoding.BigEndianUnicode`

**Comment by jhowfaithluby** [comment]
Hello @mconnew ,
I tried this solution proposed in the answers: https://github.com/dotnet/wcf/issues/1810#issuecomment-963604841
but without success, the same error reading not supported.
I'm using webapi .netcore 6 is there any way to do it without needing a wcf?

**Comment by Homaks** [comment]
> Sorry I forgot to respond to your last comment. The easiest way to do this I believe is to use the MtomMessageEncodingBindingElement. This will output a Message object. Depending on how you want to parse things, I don't know how appropriate this is to your use case. Presuming you want to minimize changes elsewhere in the code, this can be converted to an XmlDocument. Here's some example code on how to do this. You might need to tweak it for your scenario a bit if the SOAP/Envelope version is different than the default. Something like this should work for you:
> 
> ```cs
>             var mtomBE = new MtomMessageEncodingBindingElement(MessageVersion.Default, Encoding.UTF8);
>             var encoderFactory = mtomBE.CreateMessageEncoderFactory();
>             var encoder = encoderFactory.Encoder;
>             var message = encoder.ReadMessage(stream, int.MaxValue);
>             var messageBufferedCopy = message.CreateBufferedCopy(int.MaxValue);
>             var writableMessage = messageBufferedCopy.CreateMessage();
>             XmlDocument doc = new XmlDocument();
>             using (XmlWriter xmlDocWriter = doc.CreateNavigator().AppendChild())
>             {
>                 using (XmlDictionaryWriter writer = XmlDictionaryWriter.CreateDictionaryWriter(xmlDocWriter))
>                 {
>                     writableMessage.WriteMessage(writer);
>                 }
>             }
> ```
> 
> Let me know if that works for you or if you hit any problems. I couldn't test this code as I don't have an Mtom stream lying around handily to test this so it might need some tweaks.
> 
> I'm curious why you are using the MtomReader directly instead of using WCF to do the work? You can use WCF in a contractless way using the IRequestChannel interface to make a request and get a reply using Message objects. Typically you would do this if the request or reply message if a little too free form for a contract definition. Going low level like this is usually a result of not knowing how to get WCF to go a little lower level. XmlDocument isn't as performant as XmlReader (which is what WCF uses to expose the body) and I wonder if there might be a better way to achieve your end goal. I often find taking a step back and looking at the original problem which is needing to be solved can lead to a simpler/cleaner solution.

Simple answer to your question - legacy or some not standard soap services (( 
Please make a class XmlMtomReader public. You make a lot of people happy )

**Comment by Homaks** [comment]
Hello, @mconnew
Simple answer to your question (https://github.com/dotnet/wcf/issues/1810#issuecomment-963604841): legacy or some not standard soap services (( 
Please make a class XmlMtomReader public. You make a lot of people happy )
