### ISSUE TITLE
Error on using extension to import WSDL

### ISSUE THREAD

**Issue by carneirim** [dotnet/wcf#1892]
Hi,

I´m trying to reach unsucessfully the WSDL:
http://webservices.sabre.com/wsdl/tpfc/OTA_VehAvailRateLLS2.4.1RQ.wsdl

We´ve sucessfully imported the same WSDL on .net Framework.

Error message:

```
Scaffolding Code ...
Error:Error: There was a validation error on a schema generated during export:
    Source: 
    Line: 2 Column: 3
   Validation Error: The global attribute 'http://www.w3.org/XML/1998/namespace:lang' has already been declared.
Error: There was a validation error on a schema generated during export:
    Source: 
    Line: 3 Column: 3
   Validation Error: The global attribute 'http://www.w3.org/XML/1998/namespace:space' has already been declared.
Error: There was a validation error on a schema generated during export:
    Source: 
    Line: 11 Column: 3
   Validation Error: The global attribute 'http://www.w3.org/XML/1998/namespace:base' has already been declared.
Error: There was a validation error on a schema generated during export:
    Source: 
    Line: 13 Column: 3
   Validation Error: The attributeGroup 'http://www.w3.org/XML/1998/namespace:specialAttrs' has already been declared.

Failed to generate service reference.


```

**Comment by hongdai** [comment]
@carneirim Sorry to hear that you are running into the issue! We can repro it in house and will investigate the root cause.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
@carneirim We do not generate code because there are service schema validation errors, the generated code might not work in the run time. 

Could you tell me if the generated code on the full framework actually work in the run time(i.e. you can successfully use the client to call the service)? This will help us if the errors can be ignored.

Thanks,
Hong

**Comment by hongdai** [comment]
@carneirim This issue is fixed in the next release. We will ignore all WSDL import validation error messages as many customers do not own services and it's not feasible to fix the services.

**Comment by arishlabroo** [comment]
@hongdai , is there a workaround till next release? especially if windows/full-framework is not available.

**Comment by zhenlan** [comment]
@arishlabroo the fix can be obtained through VS2017 v15.5 preview.

**Comment by dmitry-pavlov** [comment]
I am still getting the error "**Failed adding Microsoft WCF Web Service Reference Provider to the project**" while trying to add WCF reference to https://webservice.nada.com/vehicles/secure/securelogin.asmx?WSDL 

Visual Studio Community 2017 - v15.8.0 Preview 1.1

```
[31.05.2018 13:19:20.277] Adding Microsoft WCF Web Service Reference Provider to the project.
[31.05.2018 13:19:20.279] Importing web service metadata ...
[31.05.2018 13:19:20.401] Number of service endpoints found: 2
[31.05.2018 13:19:20.464] Scaffolding service reference code ...
[31.05.2018 13:19:25.183] Error:An unknown error occurred while invoking the service metadata component.
Failed to generate service reference.
[31.05.2018 13:19:25.216] Done.
[31.05.2018 13:19:25.234] Failed adding Microsoft WCF Web Service Reference Provider to the project.
```

Any thoughts how to fix / workaround this?

**Comment by zhenlan** [comment]
@dmitry-pavlov thanks for reporting the issue. This might be different from the original issue of this thread. Do you mind to open a new issue?

cc: @mlacouture
