### ISSUE TITLE
[WCF Connected Services][VS2017][netstandard] Cannot add reference to ONVIF WSDL (contains non-schema/wsdl elements)

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/wcf#2104]
I am trying to add a reference to the following WSDL:

https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl

However when I click "go", the "please wait" message is displayed and the operation never completes.

This service can correctly be added by using "Add service reference" to a .Net full framework project, but I'm working on a .net standard project. What other options do I have to add my reference?

**Comment by hongdai** [comment]
@jeremyVignelles  Sorry to hear that you are running into an issue!

I'm able to repro the issue locally. We will further investigate the root cause.

Thanks,
Hong Dai

**Comment by hongdai** [comment]
@jeremyVignelles When you add the service using "Add service reference", does the generated client code function correctly?

**Comment by jeremyVignelles** [comment]
Hi, I can't do this since I am working on a .net standard project. I tried
with a full framework project and the code seems to generate correctly,
though I didn't test it

**Comment by jeremyVignelles** [comment]
Any update on this issue? Do you know when a new release of the tool will be available?

Is there any workaround so that I can work in the meantime?

**Comment by hongdai** [comment]
The operation never completes because download metadata does not complete.

You can workaround it by downloading the wsdl file locally and launch from there. 

However, after it, I've got below error message:
"The service at the following URI does not have any endpoints compatible with .Net Core apps:'C:\git\WCFTools\DeviceBinding - WS Binding.wsdl'"

This is probably because it needs WS-discovery that DotNet Core WCF runtime we depend on does not support yet. Unfortunately there is no workaround for it.

**Comment by hongdai** [comment]
The download never completes as we do not support Disco. This is the same issue as #2197

**Comment by zhenlan** [comment]
Duplicate of #2197

**Comment by mlacouture** [comment]
Looking at issue#2197 I found that this issue is not a duplicate of that one.  We will reconsider a solution for this issue.

thanks,
Miguel Lacouture

**Comment by jeremyVignelles** [comment]
Hi, what's the status of the WS-Discovery support? is it planned anytime soon?

**Comment by mlacouture** [comment]
@jeremyVignelles, this is not currently in our near-term plans, as a workaround for this problem you can download the service metadata as wsdl files and provide the wsdl to the WCF Web Service Reference tool.  

BTW: for https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl I tried downloading the service metadata using svcutil and it won't work w/o fixing up the generated files, svcutil will save schema included in the *.wsdl file in a separate *.xsd file but it won't attempt to modify the origin wsdl file to include the new xsd file.  A better option is to use the 'Add Service Reference' tool available for .NET Framework projects, this tool adds the metadata files to the project along with the Reference.cs file but these files are hidden unless you click the "Show all files" button in the Solution Explorer window.

**Comment by mlacouture** [comment]
Hi @jeremyVignelles 
I decided to investigate this issue more in depth and found out that this is not related to DISCO, I have to apologize for having made the wrong assumption, which delayed the investigation of this problem and finding a solution for it.  

I have determined that this is a bug in the tool and we will be working on a solution for it and hope to be making the fix available in a future update to Visual Studio 2017, please stay tuned.

BTW, as a clarification note, WS-Discovery is not the same as DISCO, the latter is a Microsoft-specific 
Web Services protocol that has long been superseded by WS-MetadataExchange which is the protocol the WCF Web Service Reference tool uses.

thanks,
Miguel Lacouture

**Comment by jeremyVignelles** [comment]
Thanks for coming back :smile: 
Sorry for the misunderstanding about WS-Discovery vs disco.

As a workaround, I have setup a useless class library project in .net framework with the old csproj format, and I have my library project with the new csproj format, still with .net framework that links to the Reference.cs files. this is far from ideal, but it allows me to use the new csproj format while keeping the ability to update service references.

I hope that a time will come when I can convert my projet to .netstandard :smile:

**Comment by mlacouture** [comment]
A fix for this issue is planned to be available with the release of VS 2017 Preview 4 scheduled for 02/07/2018, stay tuned.

**Comment by mlacouture** [comment]
[VS 2017 v15.6 Preview 4 ](https://www.visualstudio.com/vs/preview/)is now available, hope you can all try it.
thanks,
Miguel Lacouture

**Comment by jeremyVignelles** [comment]
Hi, I just tried to add a WCF Web Service Reference in vs 15.6.0 preview 5.0.
I tried to add the https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl url, however, the same issue is still there : after clicking "go", the download waits but never completes.

When downloading the .wsdl file manually and "browsing" it, it looks like it doesn't find the .xsd :

> Impossible de trouver une partie du chemin d'accès 'C:\ver10\schema\onvif.xsd'.

Could you please reopen this issue or tell me what I'm doing wrong?

**Comment by mlacouture** [comment]
Hi @jeremyVignelles 
I just verified and you are correct, the fix is not in v15.6 Preview 4 but in v15.7 Preview 1 which is scheduled to be available next week (3/8/2018).  Sorry about the confusion.
thanks,
