### ISSUE TITLE
Temporarily disable flaky Streaming tests then fix product and/or test bug

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#287]
The Streamed tests are failing at a very high rate, and causing our Outerloop CI runs to fail often. This is making it very hard to identify genuine failures in the OuterLoop test results. 

I recommend disabling these tests for now while we investigate the issues, so we don't mask the real failures in Outerloop. 

http://dotnet-ci.cloudapp.net/job/dotnet_wcf_outerloop/

These are the tests that regularly fail: 
```
ServiceContractTests.DefaultSettings_Echo_RoundTrips_String_Streamed
ServiceContractTests.DefaultSettings_Echo_RoundTrips_String_Streamed_Async
ServiceContractTests.DefaultSettings_Echo_RoundTrips_String_Streamed_Async_WithSingleThreadedSyncContext
```

**Comment by iamjasonp** [comment]
Might be related to #267

**Comment by roncain** [comment]
I personally think we need to make these tests work or declare streaming is DOA in beta7.  Either it is a test bug (which means we can skip these tests till we fix them) or a product bug.  If the former, I don't mind skipping. If the latter, these failures are critical to fix.   If we skip the tests due to product bugs for a feature we declared a must-have for beta7, the sense of urgency will diminish.

**Comment by zhenlan** [comment]
@shmao has root caused the issue. It appears to be a bug in networking. Let's try to get a fix from them.

**Comment by zhenlan** [comment]
@hongdai the streaming mode issues should have been fixed. Can you please validate this as part of beta-7 sign off and close this issue?

**Comment by iamjasonp** [comment]
This test is still really flaky :(

**Comment by roncain** [comment]
Even after the recent checkin to move to post-beta7 packages?  It passed for me and the CI machine, which is fairly unusual.  It would be a problem if it is still flakey post-beta7

**Comment by iamjasonp** [comment]
This was me observing flakiness as TestCop the past few days. 
I'm hoping that there will be an improvement after referencing the post-beta7 packages though.

**Comment by hongdai** [comment]
The post-beta7 packages has just checked in. I will keep an eye on it for a few days to see it's still failing.

**Comment by zhenlan** [comment]
The repo has been updated to pick up beta7 packages and we don't see this failing anymore.
