### ISSUE TITLE
WCF Debugger Issue with Client

### ISSUE THREAD

**Issue by JVarga3** [dotnet/wcf#4683]
Hello,

[Reference issue](https://github.com/dotnet/wcf/issues/4363#issuecomment-734390712)
I linked to a comment on a referenced issue as its the only comment I could find that mentions the problem I am finding. Just like gmihaescu says, if I use the debugger to look at a created WCF client I get a Channel and InnerChannel error and the client is faulted. BUT if I don't look at the serviceClient via debugger and continue through the code works. 

Example code below: I find if I am at a breakpoint and stepping through, if I look at serviceClient before the service is executed, the client breaks and is faulted. If I look at serviceClient after the response is received I can see the serviceClient.

var serviceClient = GetServiceClient();
var response = await serviceClient.ExecuteAsync()

The image is the serviceClient object when I try to look at it before the call to the service.
![image](https://user-images.githubusercontent.com/22597502/127187786-a5bbe814-bde3-459c-9af7-67f93a0e5d77.png)

Hopefully it makes sense what I wrote and maybe I am doing something wrong with the creation of the client. Just seems weird that the debugger can see serviceClient after it calls ExecuteAsync but not before. 

Thanks

**Comment by HongGit** [comment]
When you look at an object in the debugger, some of the properties have side effects, and some of the side effects could cause the channel to be defected.

Are you using .NET framework or .NET Core?  What specific information are you looking for?

**Comment by JVarga3** [comment]
.NET Core 3.1. Its just the object at its high level as shown in the image above. I've managed to get around debugging by just not looking at the client at all or at least until the response is received. It just seems weird that looking at a created client before it makes the call causes the program to crash.

**Comment by mconnew** [comment]
It looks like you're not using the latest version of the packages. The error on the Endpoint property is due to an incorrect DebuggerDisplay attribute which we fixed in a later version. Try using the latest version (4.8.1) and see if you have the same problem.

**Comment by JVarga3** [comment]
I imagine you are talking about the packages that are added when generating a connected service:
![image](https://user-images.githubusercontent.com/22597502/128713533-eafaff03-9aab-4b78-b0af-32dfdd43322a.png)

They are updated to 4.8.1 and the same issue is present.

**Comment by mconnew** [comment]
Does the Endpoint property still say "The name '_address' does not exist in the current context"?

**Comment by SayedMHaider** [comment]
For me also its showing same error: "Address=error CS0103: The name '_address' does not exist in the current context".

Packages:
![image](https://user-images.githubusercontent.com/88713965/128848558-e4b05723-4267-4102-be2b-7a720566830f.png)

**Comment by JVarga3** [comment]
So it still breaks even with the updated code if I look at the client before it calls. But what is interesting, if I let it call and get the response back and then look at the object with the debugger I see:
![image](https://user-images.githubusercontent.com/22597502/128891173-dd5d0dd6-2b4a-4960-8ad8-4f8ab9f1d2a6.png)
"The name '_address' does not exist in the current context" is still shown even though the client isn't faulted.

**Comment by mconnew** [comment]
Are you using WSHttpBinding? The default security mode is Message security which isn't supported. We do support TransportWithMessageCredentials, but we don't yet support that with Windows credentials. The issue with "The name '_address' does not exist in the current context" is because of a debugger attribute on the class which wasn't updated when the private field _address used to back the Address property was removed in preference of using an auto property. I thought this had been fixed for 4.8.1 but apparently it didn't make it in. This won't change the state of anything and is cosmetic in the debugger only. This issue has been fixed in the upcoming 4.9 release.

**Comment by jfreres** [comment]
When is 4.9 production or is this fix in the rc or preview releases of 4.9?

**Comment by mconnew** [comment]
It should be in the rc release now.

**Comment by HongGit** [comment]
Feel free to reactivate the issue if the problem persists after .NET 4.9 release.

**Comment by delfim-dacosta** [comment]
Hello,
If i try to debug CoreWCF calls from a client in .net 4.7.2 or in .net 6, i have the same problem : the channel is faulted.
Same behavior using BasicHttpBinding or NetTcpBinding.
I made a lot of tests ans i found that the problem occurs when the debugger try to evaluate a client property.

I have the following method that test a call.

1	static void Test2Http()
2	{
3	    var binding = new BasicHttpBinding(BasicHttpSecurityMode.None);
4	    ServiceReference1.HardwareConfiguratorServiceClient client = new ServiceReference1.HardwareConfiguratorServiceClient(binding, new EndpointAddress($"http://{ServerName}:5123/HardwareConfiguratorService/Main"));
5	    try
6	    {
7	        Debug.WriteLine($"State : {client.State}");
8	        string result = client.Test("Test - Http");
9	    }
10	    catch (Exception ex)
11	    {
12	        throw;
13	    }
14	}

If a set a breakpoint on the line 7 and add client in Watch window, I saw the following behavior :
	- Stepping over the line 7 show client.State as "Created"
		--  Stepping over the rest of the method run successfully
	- Stepping over the line 7 show client.State as "Created"
		--  Evaluating Client var in Watch windows for example, set the channel as Faulted (The step before on Line 7 show Created...). Exception is thrown in lien 8

**Comment by jfreres** [comment]
If local debugging does our connection string have TrustServerCertificate=true

Justin Freres

**Comment by delfim-dacosta** [comment]
@jfreres : I don't understand your comment, I don't use certificates. I have the issue connection with basicHttpBinding with no security and NetTCPBinding also.

**Comment by jfreres** [comment]
Sorry commented on wrong post.  Let me look at this later.

Justin Freres
